### PR TITLE
[resolves #31] Master build fails with javadoc errors

### LINKED ISSUE #31: Master build fails with javadoc errors
```
[ERROR] /Users/tdiesler/git/JavaBitcoindRpcClient/src/main/java/wf/bitcoin/javabitcoindrpcclient/BitcoinRPCException.java:23: error: malformed HTML
[ERROR]  * <alex@polverini.org>
[ERROR]    ^
[ERROR] /Users/tdiesler/git/JavaBitcoindRpcClient/src/main/java/wf/bitcoin/javabitcoindrpcclient/BitcoinRPCException.java:23: error: bad use of '>'
[ERROR]  * <alex@polverini.org>
[ERROR]                       ^
[ERROR] 
[ERROR] Command line was: /Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre/../bin/javadoc @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/Users/tdiesler/git/JavaBitcoindRpcClient/target/apidocs' dir.
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
```

### PR DESCRIPTION
**Pull request by tdiesler**

### CODE REVIEW

**Comment by Polve** [comment]
I'm using JDK8 and I can build fine, what are you using that creates problem? I can't understand

**Comment by Polve** [comment]
Maybe it's best to move the author/email in the pom file?

**Comment by Polve** [comment]
After a bit of thought, I removed the email address, this should solve the problem

**Comment by tdiesler** [comment]
This was showing with

```
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T21:39:06+02:00)
Maven home: /usr/local/java/apache-maven
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_151.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.4", arch: "x86_64", family: "mac"
```

**Pull request closed without merging**
