### PR TITLE
changed some methods to type object

### PR DESCRIPTION
**Pull request by hamiltino**

### CODE REVIEW

**Comment by Polve** [comment]
Hello hamiltino and thanks for your proposal.

I prefer to not use Object types because the value of this library is to have a type safe access to bitcoind, otherwise a simple wrapper with a generic map would do for all the methods.

Also, for the the "move" method you forgot the optional parameters "minconf" and "comment"

**Comment by hamiltino** [comment]
Is it possible for you to add the api calls which are missing in a way that is "type safe access". I don't know how to implement them properly, if i knew i would.

**Comment by Polve** [comment]
I've committed an implementation of getinfo, please test it and report any problems or, even better, propose a fix for them

**Comment by hamiltino** [comment]
Thank you :)

**Pull request closed without merging**
