### PR TITLE
Tests

### PR DESCRIPTION
**Pull request by frpeters**
Some tests for the functions I have uploaded, currently I'm working on signrawtransaction and hopefully make some tests for it as well.

### CODE REVIEW

**Comment by Polve** [comment]
I would like to migrate from doubles to BigDecimal to avoid possible rounding errors: do you think it's possible to begin using BigDecimals on the new methods you are implementing?

**Comment by frpeters** [comment]
Wouldn't long be enough for that?

**Comment by Polve** [comment]
In the provided example difficulty is 336899932795.8077, not good for a long

**Comment by frpeters** [comment]
Okay then!, I'll start using BigDecimal instead of double. You think it would be better to change it to current variables (like amount) too?

**Comment by Polve** [comment]
Yes, I would like it very much, if you agree.

**Comment by frpeters** [comment]
Okay! I'll look into it.

**Comment by Polve** [comment]
ping @frpeters

**Comment by tdiesler** [comment]
Merge conflict. Please update if this is still relevant.

**Pull request closed without merging**
