### PR TITLE
Add getEstimateSmartFee(int nBlocks)

### PR DESCRIPTION
**Pull request by emmanuel-florent**

### CODE REVIEW

**Comment by brunocvcunha** [comment]
+1 for this.

**Comment by brunocvcunha** [comment]
@Polve any plan to review the PRs? thanks!

**Comment by Polve** [comment]
I'm sorry I missed this one, looks good, but wouldn't be better to remove the file  JavaBitcoindRpcClient.iml ?

**Comment by brunocvcunha** [comment]
Yes. @emmanuel-florent added to .gitignore but the iml file was still pushed. Can you fix that, please?

**Comment by emmanuel-florent** [comment]
Ping :. il have been deleted :)

**Comment by Polve** [comment]
Last version already includes getEstimateSmartFee

**Comment by Polve** [comment]
I'll add getResponseMessage() in the next version

**Pull request closed without merging**
