### PR TITLE
[resolves #45] Align version to that of bitcoin core

### LINKED ISSUE #45: Align version to that of bitcoin core
It may be useful to align the version of this project to the one of bitcoin core. In that way it would be immediately obvious what scope of functionality can be expected to be supported.

### PR DESCRIPTION
**Pull request by tdiesler**

### CODE REVIEW

**Comment by Polve** [comment]
I'm unsure this is a good idea

For example we can support old, no more existing methods on latest core release, and that would work just fine for people using old nodes.

The right way[TM] to do it should be to create different interfaces, maybe one for each major release, so that the users would select the interface related to the backend they are connecting to.

For example:
interface CommonMethods {
 method1()
 method2()
 method3()
}

Interface CoreV15RPC: extends CommonMethods {
 anotherMethod()
[...]
}

Interface CoreV16RPC: extends CoreV15RPC {
 specificMethodOfV16()
...
}

**Comment by tdiesler** [comment]
Bitcoin core is very cautious about their backward compatibility and IMHO we do not need to be more cautious than that. If we align the version number it would give a clear indication that this library has been found good with the named target impl of bitcoin core. Using multiple interfaces would be over engineering it, I'd say.

But ok, we may have a different idea about backward compatibility and that shoul dbe reflected in our version scheme. For example the changes related to #50 are an improvement, but also break compatibility. If we want to use semantic versioning, this would call for a major version bump. i.e. 1.x

I'm happy to close this issue for now and open another issue where we can decide what the next version should be.

**Comment by Polve** [comment]
I understand what you say, but I don't agree with overengineering for these reasons:

- we already have an interface. Having two or more just means to have a common one which will have 99% of methods, and the other ones with only a few exceptions

- there are people (me included) that uses this library to not only connect to Bitcoin Core node but to Bitcoin Cash ones and many altcoins. Since the codebase of other coins are not always synced with the original fork having the option to handle them in the future seems nice

I don't find this blocking at all, I reopen it just to leave it as a starting point for someone interested in the implementation.

**Comment by tdiesler** [comment]
This PR still needed?

**Comment by Polve** [comment]
PR not needed, maybe we should open an issue for that?
And, btw, wht do you think about what I wrote above?

**Pull request closed without merging**
